.github/workflows/pr.yml, CHANGELOG.md, README.md, Taskfile.yml, web/themes/custom/itkdev/itkdev_base_theme/package.json
<https://leantime.itkdev.dk/dashboard/show#/tickets/showTicket/2834>
Updated theme build and adds a little documentation and tasks.
=> Theme build

CHANGELOG.md, config/sync/views.view.projects.yml
https://leantime.itkdev.dk/#/tickets/showTicket/2817
- Projects page(/view?) added
=> 2817: add projects page

CHANGELOG.md, docs/Development.md
Adds information enabling Drupal development settings.
=> Development settings

CHANGELOG.md, Taskfile.yml, config/sync/views.view.user_admin_people.yml, docker-compose.oidc.yml, docs/Development.md, web/modules/custom/ai_screening/src/Drush/Commands/Commands.php, web/modules/custom/ai_screening_fixtures_base/ai_screening_fixtures_base.info.yml, web/modules/custom/ai_screening_fixtures_base/ai_screening_fixtures_base.services.yml, web/modules/custom/ai_screening_fixtures_base/src/Fixture/GroupRelationsFixture.php, web/modules/custom/ai_screening_fixtures_base/src/Fixture/UserFixture.php, web/modules/custom/ai_screening_project_track/src/ProjectTrackAccessControlHandler.php, web/modules/custom/ai_screening_project_track/src/ProjectTrackToolAccessControlHandler.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2937#/tickets/showTicket/2937>
* Fixes entity access checks
* Adds name and department to People view
* Adds group relations fixtures
* Adds Drush command to show entity access information
=> 2937: Fixed entity access checks

CHANGELOG.md, web/themes/custom/itkdev/itkdev_project_theme/templates/components/nav-button.html.twig
https://leantime.itkdev.dk/dashboard/home?tab=ticketdetails#/tickets/showTicket/2938
Use x icon for navbutton when navigation is opened
=> 2938: Use x icon for navbutton when navigation is opened

CHANGELOG.md, config/sync/openid_connect.settings.yml, config/sync/views.view.user_admin_people.yml, web/modules/custom/ai_screening/README.md, web/modules/custom/ai_screening/src/Helper/OpenIdConnectHelper.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2959#/tickets/showTicket/2959>
* Maps name
* Shows username in People view
* Handles preferred username (and sets in to email)
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> OIDC tweaks

CHANGELOG.md, web/modules/custom/ai_screening_project/src/Helper/BlockHelper.php, web/sites/default/settings.php, web/themes/custom/itkdev/itkdev_project_theme/templates/components/project-status.html.twig
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=2964#/tickets/showTicket/2964>
* Prevents passing empty arrays (or `null`) to `min` and `max`.
* Updates default site settings to make deployment run smoother. And cleans up.
=> Handled empty arrays

CHANGELOG.md, web/themes/custom/itkdev/itkdev_project_theme/templates/components/header.html.twig
https://leantime.itkdev.dk/#/tickets/showTicket/2974
- remove include of site-search
=> 2974: remove include of site-search

.github/workflows/playwright.yml, .gitignore, CHANGELOG.md, README.md, Taskfile.yml, docker-compose.override.yml, docker-compose.playwright.yml, docs/Testing.md, package-lock.json, package.json, playwright.config.ts, tests/user.spec.ts
Adds [Playwright](https://playwright.dev/) tests to the mix.
> [!NOTE]  
> This pull request builds on https://github.com/itk-dev/ai-screening/pull/36 to make tests succeed.
=> Playwright

.github/workflows/pr.yml, .markdownlintignore, CHANGELOG.md, Taskfile.yml, composer.json, composer.lock, docs/Development.md, docs/Testing.md, web/modules/custom/ai_screening/custom_event_dispatcher/README.md, web/sites/default/settings.php, web/themes/custom/itkdev/itkdev_base_theme/README.md, web/themes/custom/itkdev/itkdev_project_theme/templates/components/new-project-button.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/node--project.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/project-track-edit-form.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/views-view-table--front.html.twig
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3002#/tickets/showTicket/3002>
* Allows calling `entity.access` in Twig templates
* Calls `entity.access` and `user.hasPermission` in select places in templates
* Fixes a Markdown linting issue and cleans up Markdown files
Before:
c58031)
After:
It's left as an exercise for the reader to find more examples.
=> Access checks in Twig

CHANGELOG.md, web/modules/custom/ai_screening_project/src/BreadcrumbBuilder.php, web/modules/custom/ai_screening_project_track/src/Entity/ProjectTrack.php, web/modules/custom/ai_screening_project_track/src/Entity/ProjectTrackTool.php, web/modules/custom/ai_screening_project_track/src/Helper/ProjectTrackToolHelper.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3008#/tickets/showTicket/3008>
* Invalidates cache when needed – hopefully …
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> Cache invalidation

config/sync/views.view.front.yml, config/sync/views.view.projects.yml
https://leantime.itkdev.dk/#/tickets/showTicket/3032
Add link to user, add submit button to filter
=> Changed views

composer.json, composer.lock, config/sync/config_ignore.settings.yml, config/sync/core.extension.yml
https://leantime.itkdev.dk/#/tickets/showTicket/3033
- Add config ignore module and config
=> Add config ignore for all webforms

CHANGELOG.md, web/themes/custom/itkdev/itkdev_project_theme/css/project-styles.css, web/themes/custom/itkdev/itkdev_project_theme/js/project-icons.js, web/themes/custom/itkdev/itkdev_project_theme/tailwind.config.js, web/themes/custom/itkdev/itkdev_project_theme/templates/components/status-messages.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/page--4xx.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/page--system--403.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/page.html.twig
https://leantime.itkdev.dk/#/tickets/showTicket/3029
- Added theming for messages
=> Added theming for messages

CHANGELOG.md, web/modules/custom/ai_screening_project/src/Plugin/Block/FrontpageStatsTopBlock.php
https://leantime.itkdev.dk/#/tickets/showTicket/3030
=> Changed caching

CHANGELOG.md, config/sync/core.entity_form_display.taxonomy_term.project_track_type.default.yml, config/sync/core.entity_view_display.taxonomy_term.project_track_type.default.yml, config/sync/field.field.taxonomy_term.project_track_type.field_configuration.yml, config/sync/field.storage.taxonomy_term.field_configuration.yml, config/sync/webform.webform.complexity_uncertainty_default.yml, web/modules/custom/ai_screening_fixtures_base/src/Fixture/ProjectTrackTermFixture.php, web/modules/custom/ai_screening_project/src/Helper/ProjectHelper.php, web/modules/custom/ai_screening_project_track/ai_screening_project_track.install, web/modules/custom/ai_screening_project_track/ai_screening_project_track.services.yml, web/modules/custom/ai_screening_project_track/src/Entity/ProjectTrack.php, web/modules/custom/ai_screening_project_track/src/Exception/Exception.php, web/modules/custom/ai_screening_project_track/src/Exception/InvalidConfigurationException.php, web/modules/custom/ai_screening_project_track/src/Exception/InvalidValueException.php, web/modules/custom/ai_screening_project_track/src/Helper/FormHelper.php, web/modules/custom/ai_screening_project_track/src/Helper/ProjectTrackTypeHelper.php, web/modules/custom/ai_screening_project_track/src/Plugin/WebformElement/WeightedElementTrait.php, web/modules/custom/ai_screening_project_track/src/Plugin/WebformElement/WeightedRadios.php, web/modules/custom/ai_screening_project_track/src/ProjectTrackInterface.php, web/modules/custom/ai_screening_project_track/tests/src/Kernel/ProjectTrackTypeHelperTest.php, web/modules/custom/ai_screening_project_track/tests/src/Kernel/WebformSubmissionProjectToolTrackComputerTest.php, web/modules/custom/ai_screening_project_track/tests/src/Unit/FormHelperTest.php
<https://leantime.itkdev.dk/TimeTable/TimeTable?showTicketModal=3071#/tickets/showTicket/3071>
* Adds configuration to project track type (taxonomy term) and requires a `dimensions` property
* Updates radios webform element to require options values for each defined dimension
* Adds tests
* `@todo` Use dimensions in calculations
Defining dimensions:
Using dimensions:
=> Project track configuration

config/sync/webform.webform.complexity_uncertainty_default.yml
Please add a link to the ticket being addressed by this change.
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
If your change affects the user interface you should include a screenshot of the result with the pull request.
=> Changed webform

CHANGELOG.md, web/modules/custom/ai_screening_reports/src/Controller/AiScreeningReportsController.php, web/modules/custom/ai_screening_reports/src/Form/CreateReport.php, web/themes/custom/itkdev/itkdev_project_theme/js/charts.js, web/themes/custom/itkdev/itkdev_project_theme/package.json, web/themes/custom/itkdev/itkdev_project_theme/templates/reports-project-track.html.twig, web/themes/custom/itkdev/itkdev_project_theme/yarn.lock
=> Added option for multiple charts and added color boxes to charts

CHANGELOG.md, web/themes/custom/itkdev/itkdev_project_theme/css/project-styles.css, web/themes/custom/itkdev/itkdev_project_theme/js/project-icons.js, web/themes/custom/itkdev/itkdev_project_theme/templates/components/project-status.html.twig, web/themes/custom/itkdev/itkdev_project_theme/templates/form/webform-element-base-html--ai-screening-static-select.html.twig
https://leantime.itkdev.dk/#/tickets/showTicket/3526
- Added availability icons and text to status
=> Updated availability

CHANGELOG.md, translations/contrib-translations.da.po, web/themes/custom/itkdev/itkdev_project_theme/templates/form/webform-element-base-html--ai-screening-static-select.html.twig
https://leantime.itkdev.dk/404/#/tickets/showTicket/4318
- Add missing translations to contrib translations
=> Added translations

.woodpecker/stg.yml, CHANGELOG.md
https://leantime.itkdev.dk/404/#/tickets/showTicket/4317
- Add itkdev-docker-compose-server run --rm phpfpm composer2 dump-autoload to woodpecker stg
=> Add dump autoload
